apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiptel
  labels:
    app: uiptel
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: uiptel
  template:
    metadata:
      labels:
        app: uiptel
    spec:
      containers:
      - name: uiptel-front
        image: anryzhov/uiptel:0.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
