apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: uiptel
  labels:
    app: front
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: front
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: ${DIGEST_IMAGE}
        imagePullPolicy: Always
        env:
          - name: NODE_ENV
            value: production
          - name: API_URL
            value: https://uiptel.com/api
          - name: DIGEST_IMAGE
            value: ${DIGEST_IMAGE}
 
        ports:
          - containerPort: 80
