apiVersion: v1
kind: Service
metadata:
  name: uiptel-front
spec:
  type: ClusterIP
  selector:
    app: uiptel-front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
