apiVersion: v1
kind: Service
metadata:
  name: uiptel
spec:
  type: NodePort
  selector:
    app: uiptel
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32180
