version:  '3.7'

services:
  front:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}
    environment: 
      NODE_ENV: production
      API_URL: https://api.uiptel.com
      DIGEST_IMAGE: 00000000FFFFFFFF
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE}
        COMMIT_ID: ${COMMIT_ID}
        VERSION: ${APP_VERSION}
        WORKDIR: /usr/share/nginx/html
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
    name: ${NAMESPACE}
