version:  '3.7'

services:
  app:
    build:
      args:
        user: ${USER_NAME}
        user_id: ${USER_UID}
        app_path: ${APP_PATH}
      dockerfile: .docker/dev/Dockerfile
    volumes:
      - /home/${USER_NAME}:/home/${USER_NAME}
      - ./:${APP_PATH}
