name: demo

on:
  push:
    branches: master

jobs:
  image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v2

      - name: Evaluate production environment
        run: |
          cat .env.prod >> $GITHUB_ENV
          echo "VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "VCS_REF=$(git log --format="%H" -n 1)" >> $GITHUB_ENV

      - name: Evaluate production image name
        run:  echo "IMAGE=${REGISTRY}/${SERVICE}_${NAMESPACE}:${VERSION}" >> $GITHUB_ENV

      - name: Build image
        run: >
            docker build -f .docker/Dockerfile -t ${IMAGE} --rm
            --build-arg WORKDIR=$APP_PATH}
            --build-arg BUILD_DATE=${BUILD_DATE}
            --build-arg VCS_REF=${VCS_REF}
            --build-arg VERSION=${VERSION}
            .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.REGISTRY }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to registry
        run: docker push ${IMAGE}
      - name: Save image digest for next jobs
        run: echo "DIGEST_IMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' ${IMAGE})" > .env.deploy
      - name: Upload .env.deploy
        uses: actions/upload-artifact@v1
        with:
          name: env
          path: .env.deploy

  image-deploy:
    env:
      KUBEHOME: ${{ github.workspace }}/.kube
      KUBECONFIG: ${{ github.workspace }}/.kube/config

    runs-on: ubuntu-latest
    needs: image-build

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v2

      - name: Download env
        uses: actions/download-artifact@v2
        with:
          name: env
      - run: cat .env.deploy >> $GITHUB_ENV

      - name: Deploy Kube config
        run: |
          mkdir -p ${KUBEHOME} \
            && echo ${{ secrets.KUBECONFIG }} | base64 -d > ${KUBECONFIG}
      
      - name: Apply deployment
        run: cat .k8s/deployment.yaml | envsubst | kubectl apply -f - \